from logging.config import fileConfig

from alembic import context

# Alembic Config object — provides access to values within the .ini file.
config = context.config

# Set up Python logging from the .ini file when running via CLI.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No SQLAlchemy metadata object is used here because CDIL keeps its runtime
# DB layer in raw sqlite3/psycopg2.  Migrations are written explicitly using
# Alembic ops rather than autogenerated from ORM models.
target_metadata = None


def _get_url() -> str:
    """Return DATABASE_URL from env, falling back to alembic.ini value.

    Environment variable takes precedence so that CI, Docker, and local dev
    can all configure the target DB without editing the ini file.
    """
    import os

    url = os.environ.get("DATABASE_URL")
    if url:
        return url
    ini_url = config.get_main_option("sqlalchemy.url")
    if not ini_url or "localhost/cdil" in ini_url:
        raise RuntimeError(
            "Set the DATABASE_URL environment variable before running Alembic.\n"
            "  export DATABASE_URL=postgresql+psycopg2://cdil:cdil@localhost:5432/cdil"
        )
    return ini_url


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout, no live DB)."""
    url = _get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect to the target DB)."""
    from gateway.app.db.alembic_engine import get_engine

    connectable = get_engine()

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
